name: Trigger update in_hapi script

on:
  workflow_dispatch:
#   schedule:
#     - cron: '17 7 * * *'

jobs:
  trigger_in_hapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run main script
        run: python update_in_hapi_key.py
        env:
          HDX_API_TOKEN: ${{ secrets.HDX_MAIN_API_TOKEN }}